import json
from pathlib import Path
import importlib.util
from . import DEVICE_MANIFEST_PATH
from controlpanel.api.commons import NodeConfig


STUB_PATH = Path(importlib.util.find_spec("controlpanel.api").origin).parent / "get_device.pyi"


def generate_get_device_stub_file() -> None:
    with open(DEVICE_MANIFEST_PATH, "r") as f:
        data: dict[str, NodeConfig] = json.load(f)

    seen_names = set()
    overloads = []
    device_names = []

    for node_name, node_config in data.items():
        for device_name, (class_name, _, _) in node_config["devices"].items():
            if device_name in seen_names:
                raise ValueError(f"Duplicate device name found: {device_name}")
            seen_names.add(device_name)

            overloads.append(
                f'@overload\ndef get_device(device_name: Literal["{device_name}"]) -> {class_name}: ...'
            )
            device_names.append(device_name)

    # Final combined file content
    boilerplate = '''"""This file has been auto-generated by the generate_stubs script"""
from typing import overload, Literal
from controlpanel.shared.base import Device
from controlpanel.api.dummy import *


'''

    footer = f"""
def get_device(device_name: str) -> Device: ...
"""

    full_code = boilerplate + "\n".join(overloads) + footer

    Path(STUB_PATH).write_text(full_code)


if __name__ == "__main__":
    generate_get_device_stub_file()
